application: dm-stat
version: 2-0-0
runtime: go
api_version: go1
skip_files:
  - ^(.*/)?.*/node_modules/.*
  - ^(.*/)?.*/test/.*
  - ^(.*/)?.*/src/.*
  - ^(.*/)?.*/build/.*

handlers:

#######################

- url: /(.*\.(gif|png|jpg|pdf))
  static_files: static/\1
  upload: static/img/(.*\.(gif|png|jpg|pdf))

- url: /(favicon.ico)
  static_files: static/img/\1
  upload: static/img/favicon.ico

- url: /css/(.*\.(css|map))
  static_files: static/css/\1
  upload: static/css/(.*\.(css|map))

- url: /js/(.*\.(js|map))
  static_files: static/js/\1
  upload: static/js/(.*\.(js|map))

- url: /font/(.*\.(eot|svg|ttf|woff))
  static_files: static/font/\1
  upload: static/font/(.*\.(eot|svg|ttf|woff))

########################

- url: /assets/scripts/(.*\.(js|map))
  static_files: static/public/assets/scripts/\1
  upload: static/public/assets/scripts/(.*\.(js|map))

- url: /
  static_files: static/public/index.html
  upload: static/public/index.html

- url: /api/.*
  script: _go_app

- url: /cron/.*
  script: _go_app